name: Go
on: [push]
jobs:
  build:
    name: Go build

    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          version: ^1.14

      - uses: actions/checkout@v2

      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports

      - run: gofmt -s -l .
      - run: goimports -l -format-only .
      - run: go vet ./...
      - run: go test -v -cover -race ./...
