name: Go
on: [push]
jobs:
  build:
    name: Go build

    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          version: ^1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go vet
        run: go vet ./...

      - name: Run tests
        run: go test -v -cover -race ./...
